codecov:
  branch: master
  status:
    project:
      default:
        enabled: true
        threshold: 0.1
    patch:
      default:
        enabled: false
    changes:
      default:
        enabled: false
