version: 2.1
orbs:
  node: circleci/node@4.3.0
jobs:
  build:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    working_directory: ~/project/packages/uxpin-merge-cli
    steps:
      - checkout:
          path: ~/project/
      - node/install:
          install-yarn: true
          node-version: 12.18.1
      - run:
          name: 'NPM: Set registry'
          command: npm set @uxpin:registry "https://registry.npmjs.org/"
      - run:
          name: 'NPM: Set authentication token'
          command: npm set //registry.npmjs.org/:_authToken "${NPM_TOKEN}"
      # Yarn install with cache
      - restore_cache:
          key: uxpin-merge-cli-dependencies-cache-{{ checksum "package.json" }}
      - run:
          name: "Install dependencies"
          command: make dependencies
      - save_cache:
          key: uxpin-merge-cli-dependencies-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      # Download test repositories with cache
      - restore_cache:
          key: uxpin-merge-cli-test-repos-{{ checksum "shell_scripts/test_resources/Makefile" }}
      - run:
          name: "Allow cloning git dependencies from github"
          command: mkdir -p ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
      - run:
          name: "Create test resources"
          command: make test-resources
      - save_cache:
          key: uxpin-merge-cli-test-repos-{{ checksum "shell_scripts/test_resources/Makefile" }}
          paths:
            - ./test/resources/repos
      # Build and test
      - run:
          name: "Check"
          command: make check
      - run:
          name: "Build"
          command: make build

  test-unit:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    working_directory: ~/project/packages/uxpin-merge-cli
    steps:
      - run:
          command: |
            while true; do
                sleep 10
                ps auxwwf
                echo "======"
            done
          background: true
      - run:
          name: "Test"
          command: make test-unit
          no_output_timeout: 30m
          environment:
            CHROME_PATH: /usr/bin/google-chrome
      - store_test_results:
          path: ./reports

  test-integration:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    working_directory: ~/project/packages/uxpin-merge-cli
    steps:
      - run:
          command: |
            while true; do
                sleep 10
                ps auxwwf
                echo "======"
            done
          background: true
      - run:
          name: "Test"
          command: make test-integration
          no_output_timeout: 30m
          environment:
            CHROME_PATH: /usr/bin/google-chrome
      - store_test_results:
          path: ./reports

workflows:
  build_and_test:
    jobs:
      - build
      - test-unit:
          requires:
            - build
      - test-integration:
          requires:
            - build
